Repository pfsense/pfsense, pull requests merged in 2018-07, with the labels that each got.

#3939 Improve/add help messages warning about bad security choices
  src/usr/local/www/vpn_ipsec_phase1.php
  src/usr/local/www/vpn_ipsec_phase2.php
Labels: Needs testing, Pending review/testing

#3952 Redmine #8592: Clarify DHCP hostname registration
  src/usr/local/www/services_dnsmasq.php
  src/usr/local/www/services_unbound.php
Labels: Pending review/testing

#3953 Extend maximum gateway monitoring probe interval
  src/usr/local/www/system_gateways_edit.php
Labels: Pending review/testing

#3955 routing, fix setting a new added gateway directly as the default
  src/usr/local/www/interfaces.php
Labels: Pending review/testing

#3956 routing, fix setting the default-route when the configured default gateway is a dynamic pppoe gateway
  src/etc/rc.newwanip
Labels: Pending review/testing

#3941 Add dummynet AQM and scheduler configuration support to pfSense Limit…
  src/etc/inc/shaper.inc
Labels: Changes requested, Needs testing, Pending review/testing

#3958 routing, add option 'automatic' for gateway selection, and allow manual ordering of gateways
  src/etc/inc/globals.inc
  src/etc/inc/gwlb.inc
  src/etc/inc/upgrade_config.inc
  src/etc/rc.openvpn
  src/usr/local/sbin/pfSense-dhclient-script
  src/usr/local/www/system_gateways.php
Labels: Pending review/testing

#3966 Fix ID issues when edit/delete DNS Forwarding rule
  src/usr/local/www/services_dnsmasq.php
Labels: Pending review/testing
