Repository pfsense/pfsense, pull requests merged in 2018-04, with the labels that each got.

#3924 filter vip usage, ipv6 vips cause invalid rules because a empty item …
  src/etc/inc/filter.inc
Labels: Changes requested, Pending review/testing

#3935 Update system_advanced_admin.php
  src/usr/local/www/system_advanced_admin.php
Labels: Changes requested

#3937 fix #8441; ipfw rules must be deleted before cp record delete
  src/etc/inc/captiveportal.inc
Labels: Pending review/testing

#3938 Bug #8469 - Fix for errant display of DHCP Server Dynamic DNS Advanced Parameters
  src/usr/local/www/services_dhcp.php
Labels: Pending review/testing
