Repository pfsense/pfsense, pull requests merged in 2020-09, with the labels that each got.

#4315 RADIUS authentication via shell/ssh. Implement #10545
  src/etc/inc/auth.inc
  src/etc/rc.bootup
  src/usr/local/www/system_usermanager_settings.php
Labels: Tested

#4427 Not destroying VTI interfaces when booting before creating a new one. Fixes #10842
  src/etc/inc/interfaces.inc
Labels: Needs to be tested

#4190 Remove extra 00 padding of VTI interface names. Issue #9592
  src/etc/inc/globals.inc
  src/etc/inc/gwlb.inc
  src/etc/inc/interfaces.inc
  src/etc/inc/ipsec.inc
  src/etc/inc/upgrade_config.inc
  src/usr/local/www/vpn_ipsec.php
  src/usr/local/www/vpn_ipsec_phase1.php
  src/usr/local/www/vpn_ipsec_phase2.php
Labels: Needs to be tested

#4400 Add build_mask_rules for scheduler
  src/etc/inc/shaper.inc
Labels: Changes requested

#4176 Add option to increase parallel IKEv1 Phase 2 rekeys. Issue #9331
  src/etc/inc/ipsec.inc
  src/usr/local/www/vpn_ipsec_settings.php
Labels: Needs to be tested

#4273 OpenVPN+RADIUS+Cisco-AVPair IPv6 ACL. Issue #10454
  src/etc/inc/openvpn.attributes.php
Labels: Tested
